name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm --filter webapp exec prisma generate

      - name: Run unit tests
        run: pnpm test:unit

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm --filter webapp exec prisma generate

      - name: Run unit tests
        run: pnpm test:unit

  # e2e:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 9.0.0

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Install Playwright browsers
  #       run: pnpm --filter webapp exec playwright install --with-deps

  #     - name: Build applications
  #       run: pnpm build

  #     - name: Run E2E tests
  #       run: pnpm test:e2e
  #       env:
  #         AUTH_SECRET: "test-secret-for-github-actions"
  #         NEXTAUTH_URL: "http://localhost:3000"
  #         DATABASE_URL: "file:./test.db"
  #         OPENAI_API_KEY: "dummy-key-for-testing"

  #     - name: Upload test results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: apps/webapp/playwright-report/
  #         retention-days: 30

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm --filter webapp exec prisma generate

      - name: Build
        run: pnpm build
        env:
          # Database
          DATABASE_URL: 'file:./test.db'
          # Auth
          AUTH_SECRET: 'test-secret-for-github-actions'
          NEXTAUTH_URL: 'http://localhost:3000'
          # Bridge API (dummy values for build)
          BRIDGE_CLIENT_ID: 'dummy-client-id'
          BRIDGE_CLIENT_SECRET: 'dummy-client-secret'
          # Powens API (dummy values for build)
          POWENS_CLIENT_ID: 'dummy-powens-client-id'
          POWENS_CLIENT_SECRET: 'dummy-powens-client-secret'
          POWENS_PARTNER_PASSWORD: 'dummy-powens-password'
          POWENS_API_BASE: 'https://sandbox.biapi.pro'
          # Callback URLs
          BRIDGE_CALLBACK_URL: 'http://localhost:3000/api/bridge/callback'
          POWENS_CALLBACK_URL: 'http://localhost:3000/api/powens/callback'
          # Email service
          RESEND_API_KEY: 'dummy-resend-key'
          AUTH_RESEND_FROM: 'test@example.com'
          # Google OAuth (dummy values for build)
          AUTH_GOOGLE_ID: 'dummy-google-client-id'
          AUTH_GOOGLE_SECRET: 'dummy-google-client-secret'
          # Other APIs
          OPENAI_API_KEY: 'dummy-openai-key'
          # Vercel
          VERCEL_PROJECT_PRODUCTION_URL: 'localhost:3000'
          PORT: '3000'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            apps/*/build
            apps/*/.next
          retention-days: 1
